shortName: aegitops
fullName: AnsibleEdgeGitops
webHookName: ''
owners:
  - Martin Jackson
triggers:
  branches:
  - name: main
    versions:
    - '4.12'
    - '4.11'
  - name: 'v1.1'
    versions:
    - '4.11'
    - '4.10'

  openshift:
  - version: '4.12'
    branch: main
    platforms:
      - aws
  - version: '4.11'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.10'
    branch: 'v1.1'
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - openshift-gitops: main
