shortName: manuela
fullName: Manuela
webHookName: ''
owners:
  - claudiol
triggers:
  branches:
  - name: main
    versions:
    - '4.12'
    - '4.11'
  - name: 'v2.2'
    versions:
    - '4.10'
    - '4.9'
    - '4.8'
  - name: 'v2.3'
    versions:
    - '4.11'


  openshift:
  - version: '4.12'
    branch: main
    platforms:
      - aws
  - version: '4.11'
    branch: 'v2.3'
    platforms:
      - gcp
  - version: '4.10'
    branch: 'v2.2'
    platforms:
      - azure
    buildType: stable
  - version: '4.9'
    branch: 'v2.2'
    platforms:
      - aws
    buildType: stable
  - version: '4.8'
    branch: 'v2.2'
    platforms:
      - gcp
    buildType: stable

  subscriptions:
  - openshift-gitops: main
