shortName: medicaldiag
fullName: MedicalDiagnosis
webHookName: 'medical-diagnosis'
owners:
  - jrickard
triggers:
  branches:
  - name: main
    versions:
    - '4.12'
  - name: 'stable-4.11-v2.3'
    versions:
    - '4.10'
    - '4.11'

  openshift:
  - version: '4.12'
    branch: main
    platforms:
      - azure
    buildType: stable
  - version: '4.11'
    buildType: stable
    branch: 'stable-4.11-v2.3'
    platforms:
      - aws
  - version: '4.10'
    branch: 'stable-4.11-v2.3'
    platforms:
      - gcp
    buildType: stable

  github:
    - version: '4.11'
      platforms:
        - azure

  subscriptions:
  - name: gitops
    branch: main
