shortName: devsecops
fullName: MulticlusterDevSecOps
webHookName: ''
owners:
  - whenry
  - jrickard
triggers:
  branches:
  - name: main
    versions:
    - '4.12'
    - '4.11'

  openshift:
  - version: '4.12'
    branch: main
    platforms:
      - aws
      - azure
      - gcp
    buildType: stable
  - version: '4.11'
    branch: main
    platforms:
      - aws
      - azure
      - gcp
    buildType: stable

  subscriptions:
  - openshift-gitops: main

