shortName: mcgitops
fullName: MultiCloudGitops
webHookName: ''
owners:
  - bandini
triggers:
  branches:
  - name: main
    versions:
    - '4.12'
    - '4.11'
    - '4.10'
  - name: 'v1.0'
    versions:
    - '4.9'

  openshift:
  - version: '4.12'
    branch: main
    platforms:
      - aws
  - version: '4.11'
    branch: main
    platforms:
      - gcp
    buildType: stable
  - version: '4.10'
    branch: main
    platforms:
      - azure
    buildType: stable
  - version: '4.9'
    branch: 'v1.0'
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - openshift-gitops: main
